### PR TITLE
Add a tiny filter.

### PR DESCRIPTION
**Pull request by rseac**
Completing the issue.

### CODE REVIEW

**Comment by inukshuk** [comment]
Please use a `span` element with `class="tiny"` instead of a `p` with inline styles. Users can then style the element appropriately using stylesheets.

**Comment by rseac** [comment]
@inukshuk I guess it should be ready now.

**Comment by inukshuk** [comment]
Still missing the quotation marks around the `tiny` classname I think?

**Comment by inukshuk** [comment]
Do you have any other PRs planned? If so I'll hold off on publishing a release, otherwise I can push this one out right away.

**Pull request merged**
