### PR TITLE
Added brief documentation new file repo behavior.

### PR DESCRIPTION
**Pull request by ShadenSmith**
Just adding some documentation to `README.md` concerning the new file repository behavior.

### CODE REVIEW

**Comment by ShadenSmith** [comment]
So it looks like `links['slides.pdf']` is the correct way to access with a "." delimiter. The documentation is updated to reflect that. But, we have inconsistencies now with `links.pdf` and `links['slides.pdf']`. Should we change everything to use the `['']` syntax?

**Comment by inukshuk** [comment]
Excellent, thanks.

I have no strong opinion on the syntax in the example either way -- it is both valid Liquid syntax after all.

**Comment by edgemaster** [comment]
Could we additionally qualify the readme the version of Jekyll this feature appears in?

**Comment by edgemaster** [comment]
Ah, noticed it's already made it into 5.9, will amend the text myself.

**Pull request merged**
