### PR TITLE
add bibtex files to dependency tree

### LINKED ISSUE #96: add .bib file as dependency for pages where bibliography tag is used (Jekyll 3)
Jekyll 3 uses dependency tracking to speed up incremental builds. Jekyll-scholar doesn't seem to support that. Whenever a page uses the bibliography tag, a dependency on the .bib file used should be added. My Ruby knowledge is rather limited, so I don't know how to get the .bib file name in the render() method. 

Here is how dependencies are handled for the include tag's render method in jekyll 3:
```
        # Add include to dependency tree
        if context.registers[:page] and context.registers[:page].has_key? "path"
          site.regenerator.add_dependency(
            site.in_source_dir(context.registers[:page]["path"]),
            path
          )
        end
```

### PR DESCRIPTION
**Pull request by mamoll**
Attempt to close #96. Keep in mind that I know very little about Ruby or Jekyll-Scholar.

### CODE REVIEW

**Comment by inukshuk** [comment]
It looks good to me; have you tested this with a Jekyll 3 setup? I assume the point of this that the page is not regenerated if neither template nor bib files have changed, correct? I am happy to merge this if it works for you.

**Comment by mamoll** [comment]
Yes, it works for me. In my case, `jekyll clean && jekyll build` takes roughly 30 seconds, while calling `jekyll build` after the first build takes only 1.3 seconds. I tested that it works by doing `touch mybibfile.bib && jekyll build`.

**Comment by inukshuk** [comment]
Awesome!

Do you want me to put this into another pre-release or are you fine working from master or your own branch until jekyll 3 comes out?

**Comment by mamoll** [comment]
I am fine working from my own branch.

**Pull request merged**
