### PR TITLE
Take into account source directory from original configuration for the generated repository links

### LINKED ISSUE #151: Take into acount source tag from configuration yml in scholar publications repository link
I have a non-standard source defined in my _config.yml. However, now the links are either not shown (when the repository directory is below the source dir) or the links are broken (when the repository directory is in the root), as the files are not copied to the site (they are below the source dir).

### PR DESCRIPTION
**Pull request by JoostvanPinxten**
Fixes #151.

I'm willing to bet that there's some functionality I've missed for commit 93cb79981f01b1faaed5cd5f092ab3441d6922f7 to make it look a lot nicer than what I did.

Please suggest the proper way to do this, or what this should look like.

### CODE REVIEW

**Comment by JoostvanPinxten** [comment]
Btw, I forgot to sync my fork before committing the changes.

**Comment by JoostvanPinxten** [comment]
Okay, can anyone suggest how to improve the test environment? This indeed does not work (I had a more elaborate version of the check before, but I can't recover it right now)

**Comment by JoostvanPinxten** [comment]
I think I'm getting the hang of this. After accepting this merge, can you give me write access to the repo as well?

**Comment by inukshuk** [comment]
Looks good, thanks!

This is an ['open' open source](http://openopensource.org/) project so I'll gladly give you write permissions (you've earned it!). To add tests (if feasible) is a big asset because it helps other maintainers notice if they break something you added -- you're already doing that, so that's cool.

At the moment only I can push releases to RubyGems, so you have to ping me -- once you've made a few more commits we can add you to RubyGems, too.

Happy hacking!

**Pull request merged**
