### PR TITLE
Remove use_raw_bibtex_entry option

### PR DESCRIPTION
**Pull request by stevecheckoway**
Jekyll 4 does not render Liquid markup from included BibTeX files any
longer. This obviates the need for adding `{%raw%}` around an entry's
`bibtex` field. Indeed, adding it causes `{%raw%}` and `{%endraw%}` to
appear in the output.

This commit adds a warning if the `use_raw_bibtex_entry` key appears in
the jekyll-scholar options, regardless of the value of the entry.

### CODE REVIEW

**Comment by stevecheckoway** [comment]
This is a follow up to the discussion in #273.

**Comment by dirteat** [comment]
Hi there,
just updated to jekyll 4, I used to have use_raw_bibtex_entry to true and all things related to jekyll-scholar are now broken :(

For instance, I cannot make {% bibliography --file afile.bib %}  to work anymore, it seems to pick a random .bib file among the many I have.

I have already removed all yaml header in .bib file, which otherwise trigger errors with the {{}} bibtex entry.

Any advice welcome, I cannot find anything in the changelog that would explain this.
Thanks!

**Comment by stevecheckoway** [comment]
@dirteat it's probably best to file an issue.

I'm a little surprised that ever worked though. My recollection of how Liquid markup works is that your updated example should call whichever function was registered for `bibliography` and then it would get `--file {{ member.bibfile }}` as an argument and it would be responsible for parsing that. In particular, I wouldn't expect it to do more liquid rendering on it to produce a file name.

**Comment by dirteat** [comment]
Ok, I'll open a new issue.
I reverted back to jekyll 3.8.6 and jekyll-scholar 5.16.0, and that really works.

The website is actually: https://curl.group

you can check the output on "members" menu, each get his own biblio generated by
``
{% bibliography --file {{ member.bibfile }} %}
``
where member.bibfile is defined in some markdown text file for each "member".

**Comment by inukshuk** [comment]
> My recollection of how Liquid markup works is that your updated example should call whichever function was registered for `bibliography` and then it would get `--file {{ member.bibfile }}` as an argument and it would be responsible for parsing that. In particular, I wouldn't expect it to do more liquid rendering on it to produce a file name.

Yes, jekyll-scholar interpolates the parameters additionally. 

This is probably unrelated to the raw bibtex option? Or is the whole thing `{% bibliography ... %}` embedded in a bibtex file?

**Comment by dirteat** [comment]
You're right, it is unrelated to raw bibtex; I deactivated the option in scholar 5.16.0 / jekyll 3.8.6 and everything works fine. The whole thing is in a layout, not in a bibtex file. I've open a new issue about it.

**Comment by inukshuk** [comment]
Hmm, it's possible that the fact that it is in the layout is the cause of the problem. Maybe jekyll changed something about the way the layout is evaluated. You say above that the interpolation happens just once (one file is picked) so maybe that's some kind of optimization jekyll does: render that part of the layout and then re-use the result. You would have to make sure that this part of the layout is rendered every time the `member` variable changes.

**Pull request merged**
