### PR TITLE
 Support globbing to find all .bib and .bibtex files in the source directory

### PR DESCRIPTION
**Pull request by alzeih**
Using the following in `_config.yml`:

```
scholar:
  bibliography: glob
```
Will automatically find all files under `source` that are named `**/*.bib` or `**/*.bibtex` .

This means specifying `--file` for liquid tags can be omitted, e.g:

```
{% cite a --file a.bib %}
{% cite b --file b.bib %}
{% bibliography --cited --file a.bib --file b.bib %}
```
can be written as
```
{% cite a %}
{% cite b %}
{% bibliography --cited %}
```

This also means details pages are created for all entries in all bibliographies.

### CODE REVIEW

**Comment by alzeih** [comment]
Ah, CI fails as ruby 2.4 Dir.glob doesn't support `base:` Tests pass for me with ruby 2.5.

https://ruby-doc.org/core-2.4.1/Dir.html#method-c-glob
https://ruby-doc.org/core-2.5.0/Dir.html#method-c-glob

**Comment by inukshuk** [comment]
Awesome!

I wonder if, instead of using the keyword `glob` we could support setting paths using wildcards in the `bibliography` option; if there is an `*` in the string, we pass it to `Dir.glob` and otherwise use it as is. What do you think?

**Comment by alzeih** [comment]
Good idea! I've updated the PR.

(If you are happy, I'll squash the commits before merge)

**Comment by inukshuk** [comment]
Looks great, thanks!

Would you like to have write access to the repository? Everyone who's made meaningful contributions is welcome!

**Pull request merged**
